# Generated by Django 5.2.17 on 2026-09-18 00:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('event', models.CharField(choices=[('ready_for_review', 'ready_for_review'), ('approved', 'approved'), ('fatigued', 'fatigued'), ('overdue', 'overdue')], default='ready_for_review', max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('notify', 'notify'), ('refresh_recommendation', 'refresh_recommendation')], default='notify', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='running', max_length=200)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
