# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('catalog', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automations.automationrule'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='automationrunstep',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='automationrunstep',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automations.automationrun'),
        ),
        migrations.AddField(
            model_name='automationrunstep',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(fields=('rule', 'event_id'), name='automation_once'),
        ),
    ]
