# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, default='', max_length=200)),
                ('object_type', models.CharField(blank=True, default='', max_length=200)),
                ('object_id', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, default='', max_length=200)),
                ('object_type', models.CharField(blank=True, default='', max_length=200)),
                ('object_id', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
