# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreativeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreativeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('variant', 'variant'), ('refresh', 'refresh'), ('remake', 'remake'), ('derivative', 'derivative'), ('localization', 'localization')], default='variant', max_length=40)),
                ('hypothesis', models.TextField(blank=True)),
                ('what_changed', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('version_type', models.CharField(choices=[('original', 'original'), ('revision', 'revision'), ('refresh', 'refresh')], default='original', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('changes_requested', 'changes_requested'), ('approved', 'approved'), ('published', 'published')], default='draft', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creative_type', models.CharField(choices=[('video', 'video'), ('image', 'image'), ('audio', 'audio'), ('document', 'document')], default='video', max_length=40)),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in_production', 'in_production'), ('ready_for_review', 'ready_for_review'), ('changes_requested', 'changes_requested'), ('approved', 'approved'), ('published', 'published'), ('refresh_requested', 'refresh_requested')], default='new', max_length=40)),
                ('outcome', models.CharField(blank=True, default='', max_length=200)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
