# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('creatives', '0001_initial'),
        ('requests_app', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='requests_app.requestdeliverable'),
        ),
        migrations.AddField(
            model_name='creative',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creative',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='creative',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='requests_app.creativerequest'),
        ),
        migrations.AddField(
            model_name='creative',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='creative',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='creativecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativecomment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='creativecomment',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativecomment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='creativefeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativefeedback',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='creativefeedback',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='creativerelationship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativerelationship',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='creativerelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativerelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativerelationship',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='creativeversion',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='creativeversion',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativeversion',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativeversion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='creativefeedback',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion'),
        ),
        migrations.AddField(
            model_name='creativecomment',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion'),
        ),
        migrations.AddField(
            model_name='creative',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion'),
        ),
        migrations.AddField(
            model_name='creative',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion'),
        ),
        migrations.AddConstraint(
            model_name='creativerelationship',
            constraint=models.UniqueConstraint(fields=('parent', 'child', 'relationship'), name='creative_relationship'),
        ),
        migrations.AddConstraint(
            model_name='creativerelationship',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='no_self_lineage'),
        ),
        migrations.AddConstraint(
            model_name='creativeversion',
            constraint=models.UniqueConstraint(fields=('creative', 'version_number'), name='creative_version_number'),
        ),
    ]
