# Generated by Django 5.2.17 on 2026-09-19 03:43

from django.conf import settings
from django.db import migrations, models
from django.db.models import Max
from uuid import uuid5


def split_legacy_executions(apps, schema_editor):
    """Preserve every creative and planned execution; never merge/delete history."""
    Deliverable = apps.get_model('requests_app', 'RequestDeliverable')
    Assignment = apps.get_model('requests_app', 'RequestDeliverableAssignment')
    Creative = apps.get_model('creatives', 'Creative')
    Request = apps.get_model('requests_app', 'CreativeRequest')
    Member = apps.get_model('workspaces', 'WorkspaceMembership')
    affected = set()
    for original in list(Deliverable.objects.order_by('request_id', 'sequence')):
        creatives = list(Creative.objects.filter(deliverable=original).order_by('created_at', 'pk'))
        count = max(original.quantity, len(creatives), 1)
        if count == 1:
            continue
        affected.add(original.request_id)
        Deliverable.objects.filter(pk=original.pk).update(legacy_quantity=original.quantity, quantity=1)
        fields = {f.attname: getattr(original, f.attname) for f in Deliverable._meta.fields
                  if f.name not in ['id', 'created_at', 'updated_at', 'sequence', 'quantity', 'legacy_quantity', 'title', 'status']}
        highest = Deliverable.objects.filter(request_id=original.request_id).aggregate(n=Max('sequence'))['n'] or 0
        for index in range(count):
            creative = creatives[index] if index < len(creatives) else None
            status = creative.status if creative else ('assigned' if original.assigned_editor_id else 'new')
            if index == 0 and status in ['new', 'assigned'] and original.status not in ['new', 'assigned']:
                status = original.status
            if index == 0:
                Deliverable.objects.filter(pk=original.pk).update(status=status)
                continue
            sibling, created = Deliverable.objects.get_or_create(
                pk=uuid5(original.pk, f'creative-execution:{index+1}'),
                defaults={**fields, 'sequence': highest+index, 'quantity': 1, 'status': status,
                          'title': f'{original.title[:175]} (execution {index+1})'},
            )
            for assignment in Assignment.objects.filter(deliverable=original):
                Assignment.objects.get_or_create(deliverable=sibling, user_id=assignment.user_id,
                    role=assignment.role, defaults={'workspace_id': assignment.workspace_id,
                    'brand_id': assignment.brand_id, 'notes': assignment.notes})
            if creative:
                Creative.objects.filter(pk=creative.pk).update(deliverable=sibling)
            if created:
                print(f'Preserved execution: deliverable={original.pk} sibling={sibling.pk} creative={creative.pk if creative else "planned"}')
    # Historical migration owns its frozen rollup; runtime services are not imported.
    # Correct existing partial assignment states too, without changing downstream states.
    for child in Deliverable.objects.filter(status__in=['new', 'assigned']):
        member = Member.objects.filter(workspace_id=child.workspace_id, user_id=child.assigned_editor_id,
            user__is_active=True, active=True, role__in=['manager', 'editor']).first()
        valid = member and (not member.brand_restricted or member.brands.filter(pk=child.brand_id).exists())
        Deliverable.objects.filter(pk=child.pk).update(status='assigned' if valid else 'new')
        affected.add(child.request_id)
    for request in Request.objects.filter(pk__in=affected):
        states = list(Deliverable.objects.filter(request=request).values_list('status', flat=True))
        if all(s == 'published' for s in states):
            status = 'published'
        elif all(s in ['approved', 'published'] for s in states):
            status = 'approved'
        elif 'changes_requested' in states:
            status = 'changes_requested'
        elif all(s in ['ready_for_review', 'approved', 'published'] for s in states):
            status = 'ready_for_review'
        elif any(s not in ['new', 'assigned'] for s in states):
            status = 'in_production'
        else:
            status = 'assigned' if all(s == 'assigned' for s in states) else 'new'
        Request.objects.filter(pk=request.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_platform_catalog'),
        ('creatives', '0002_initial'),
        ('requests_app', '0005_requestdeliverable_legacy_quantity'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(split_legacy_executions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='creative',
            constraint=models.UniqueConstraint(fields=('deliverable',), name='one_creative_per_deliverable'),
        ),
    ]
