# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('creatives', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('google_drive', 'google_drive'), ('local', 'local')], default='google_drive', max_length=40)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('root_folder_id', models.CharField(blank=True, default='', max_length=200)),
                ('shared_drive_id', models.CharField(blank=True, default='', max_length=200)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('scopes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('disconnected', 'disconnected'), ('connected', 'connected'), ('error', 'error')], default='disconnected', max_length=40)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('change_token', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('local', 'local'), ('google_drive', 'google_drive')], default='local', max_length=40)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('mime_type', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=200)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('duration', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('parents', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('master', 'master'), ('source', 'source'), ('thumbnail', 'thumbnail'), ('subtitle', 'subtitle'), ('export', 'export'), ('reference', 'reference'), ('attachment', 'attachment')], default='master', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
                ('storage_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageobject')),
            ],
        ),
        migrations.CreateModel(
            name='ContentIndexEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('transcript', 'transcript'), ('ocr', 'ocr'), ('note', 'note')], default='transcript', max_length=40)),
                ('machine_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='ar', max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageobject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('start', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('end', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='catalog.tag')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageobject')),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='running', max_length=200)),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('master', 'master'), ('source', 'source'), ('thumbnail', 'thumbnail'), ('subtitle', 'subtitle'), ('export', 'export'), ('reference', 'reference'), ('attachment', 'attachment')], default='master', max_length=40)),
                ('provider', models.CharField(choices=[('google_drive', 'google_drive'), ('youtube', 'youtube')], default='google_drive', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('initializing', 'initializing'), ('uploading', 'uploading'), ('verifying', 'verifying'), ('complete', 'complete'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='queued', max_length=40)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('session_encrypted', models.TextField(blank=True)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('privacy', models.CharField(choices=[('private', 'private'), ('unlisted', 'unlisted'), ('public', 'public')], default='private', max_length=40)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('storage_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageobject')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClipUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.clip')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clip', 'version'), name='clip_usage')],
            },
        ),
        migrations.CreateModel(
            name='DriveFolderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=200)),
                ('entity_id', models.UUIDField()),
                ('folder_role', models.CharField(blank=True, default='', max_length=200)),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'entity_type', 'entity_id', 'folder_role'), name='drive_folder_identity')],
            },
        ),
        migrations.AddConstraint(
            model_name='storageobject',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='storage_external_identity'),
        ),
        migrations.AddConstraint(
            model_name='creativefile',
            constraint=models.UniqueConstraint(fields=('version', 'storage_object', 'role'), name='creative_file_identity'),
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start')), ('start__gte', 0)), name='clip_interval'),
        ),
    ]
