# Generated by Django 5.2.17 on 2026-09-19 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_platform_catalog'),
        ('storage', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveNameReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.CharField(max_length=100)),
                ('parent_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('base_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='storageconnection',
            name='auto_upload_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storageobject',
            name='upload_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='storageconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('auto_upload_default', True)), fields=('workspace', 'brand'), name='one_auto_drive_destination'),
        ),
        migrations.AddField(
            model_name='drivenamereservation',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='drivenamereservation',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.storageconnection'),
        ),
        migrations.AddField(
            model_name='drivenamereservation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='drivenamereservation',
            constraint=models.UniqueConstraint(fields=('connection', 'identity'), name='drive_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='drivenamereservation',
            constraint=models.UniqueConstraint(fields=('connection', 'parent_id', 'name'), name='drive_sibling_name'),
        ),
    ]
