# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('creatives', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='brand',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='namingtemplate',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='namingtemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='tag',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.taxonomy'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='brand_slug'),
        ),
    ]
