# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('guidelines', 'guidelines'), ('facts', 'facts'), ('allowed_claims', 'allowed_claims'), ('forbidden_claims', 'forbidden_claims'), ('audience', 'audience'), ('tone', 'tone'), ('platform', 'platform'), ('campaign', 'campaign')], default='guidelines', max_length=40)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'approved'), ('archived', 'archived')], default='draft', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('proposed_change', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='proposed', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextCreativeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
