# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('context_hub', '0001_initial'),
        ('creatives', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcreativelink',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='contextcreativelink',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='contextdocumentversion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contextdocumentversion',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='contextdocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='context_hub.contextdocument'),
        ),
        migrations.AddField(
            model_name='contextdocumentversion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='context_hub.contextdocumentversion'),
        ),
        migrations.AddField(
            model_name='contextcreativelink',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='context_hub.contextdocumentversion'),
        ),
        migrations.AddField(
            model_name='creativeproposal',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='creativeproposal',
            name='resulting_creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativeproposal',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative'),
        ),
        migrations.AddField(
            model_name='creativeproposal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='contextdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='context_version'),
        ),
    ]
