# Generated by Django 5.2.17 on 2026-09-18 15:56

from django.db import migrations, models


def update_default(apps, schema_editor):
    apps.get_model("accounts", "UserProfile").objects.filter(timezone="Africa/Lagos").update(timezone="Africa/Algiers")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Africa/Algiers', max_length=80),
        ),
    ]
