# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('creatives', '0001_initial'),
        ('storage', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'normal'), ('high', 'high'), ('urgent', 'urgent'), ('low', 'low')], default='normal', max_length=40)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in_production', 'in_production'), ('ready_for_review', 'ready_for_review'), ('changes_requested', 'changes_requested'), ('approved', 'approved'), ('published', 'published'), ('refresh_requested', 'refresh_requested')], default='new', max_length=40)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.campaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('platforms', models.ManyToManyField(blank=True, to='catalog.platform')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestSourceMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('note', 'note'), ('link', 'link'), ('file', 'file'), ('drive', 'drive')], default='note', max_length=40)),
                ('url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='requests_app.creativerequest')),
                ('storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storageobject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('creative_type', models.CharField(choices=[('video', 'video'), ('image', 'image'), ('audio', 'audio'), ('document', 'document')], default='video', max_length=40)),
                ('aspect_ratio', models.CharField(blank=True, default='9:16', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('duration_target', models.PositiveIntegerField(default=0)),
                ('requirements', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in_production', 'in_production'), ('ready_for_review', 'ready_for_review'), ('changes_requested', 'changes_requested'), ('approved', 'approved'), ('published', 'published'), ('refresh_requested', 'refresh_requested')], default='new', max_length=40)),
                ('assigned_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.platform')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='requests_app.creativerequest')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'sequence'), name='deliverable_sequence'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='positive_quantity')],
            },
        ),
        migrations.CreateModel(
            name='SourceMaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='requests_app.requestsourcematerial')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='source_usage')],
            },
        ),
    ]
