# Generated by Django 5.2.17 on 2026-09-18 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('requests_app', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creativerequest',
            options={},
        ),
        migrations.AddField(
            model_name='creativerequest',
            name='submission_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='creativerequest',
            name='submission_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='creativerequest',
            index=models.Index(fields=['workspace', 'status'], name='requests_ap_workspa_d9104a_idx'),
        ),
        migrations.AddIndex(
            model_name='creativerequest',
            index=models.Index(fields=['workspace', 'due_date'], name='requests_ap_workspa_5be36d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestdeliverable',
            index=models.Index(fields=['assigned_editor', 'status'], name='requests_ap_assigne_9b5fd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='creativerequest',
            constraint=models.UniqueConstraint(fields=('workspace', 'requester', 'submission_key'), name='request_submission_key'),
        ),
    ]
