# Generated by Django 5.2.17 on 2026-09-18 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_platform_catalog'),
        ('requests_app', '0002_alter_creativerequest_options_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeliverable',
            name='hook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestdeliverable',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestdeliverable',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RequestDeliverableAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('editor', 'editor'), ('filming_responsible', 'filming_responsible'), ('scriptwriter', 'scriptwriter'), ('designer', 'designer'), ('photographer', 'photographer'), ('voice_over', 'voice_over'), ('content_creator', 'content_creator'), ('other', 'other')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='requests_app.requestdeliverable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_assignments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deliverable', 'user', 'role'), name='deliverable_person_role'), models.UniqueConstraint(condition=models.Q(('role', 'editor')), fields=('deliverable',), name='deliverable_primary_editor')],
            },
        ),
    ]
