# Generated by Django 5.2.17 on 2026-09-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_backfill_primary_editor_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeliverable',
            name='legacy_quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
