# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('creatives', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('meta', 'meta'), ('tiktok', 'tiktok'), ('google_ads', 'google_ads')], default='meta', max_length=40)),
                ('account_id', models.CharField(blank=True, default='', max_length=200)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disconnected', 'disconnected'), ('connected', 'connected'), ('error', 'error')], default='disconnected', max_length=40)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('meta', 'meta'), ('tiktok', 'tiktok'), ('google_ads', 'google_ads')], default='meta', max_length=40)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('waiting', 'waiting'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='queued', max_length=40)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('error', models.TextField(blank=True)),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('destination', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.adconnection')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('operation', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('succeeded', 'succeeded'), ('uncertain', 'uncertain'), ('failed', 'failed')], default='pending', max_length=40)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=200)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.publishjob')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'operation'), name='publish_operation')],
            },
        ),
    ]
