import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {api,post,label,relationLabel,type Item,type Page} from './api'
import {useI18n} from './i18n'
import {ErrorBox,Modal,Loading} from './components'

const responsibilities=['editor','filming_responsible','scriptwriter','designer','photographer','voice_over','content_creator','other']
export function DeliverableTeam({workspace,deliverable,canManage,canAssignEditor}:{workspace:string;deliverable:Item;canManage:boolean;canAssignEditor:boolean}){
 const {t}=useI18n();const client=useQueryClient();const [editing,setEditing]=useState<Item|null|undefined>();const [person,setPerson]=useState('');const [role,setRole]=useState('filming_responsible');const [notes,setNotes]=useState('')
 const query=useQuery({queryKey:['deliverable-team',workspace,deliverable.id],queryFn:()=>api<Page>(`deliverable-assignments/?deliverable=${deliverable.id}`,workspace)})
 const users=useQuery({queryKey:['assignment-people',workspace,deliverable.brand],queryFn:()=>api<Page>(`users/?brand=${deliverable.brand}`,workspace),enabled:canManage||canAssignEditor})
 const mutation=useMutation({mutationFn:()=>api(`deliverable-assignments/${editing?editing.id+'/':''}`,workspace,{method:editing?'PATCH':'POST',body:JSON.stringify({deliverable:deliverable.id,user:person,role,notes})}),onSuccess:()=>{setEditing(undefined);void client.invalidateQueries()}})
 const remove=useMutation({mutationFn:(row:Item)=>post(`deliverable-assignments/${row.id}/actions/remove/`,workspace,{}),onSuccess:()=>void client.invalidateQueries()})
 const edit=(row:Item|null)=>{setEditing(row);setPerson(String(row?.user||''));setRole(String(row?.role||'filming_responsible'));setNotes(String(row?.notes||''));mutation.reset()}
 return <div className="deliverable-team"><div className="section-heading"><h4>{t('teamAssignments')}</h4>{(canManage||canAssignEditor)&&<button className="button secondary" onClick={()=>edit(null)}>{t('addAssignment')}</button>}</div>{query.isPending?<Loading/>:query.error?<ErrorBox error={query.error}/>:query.data.results.map(row=><article className="team-assignment" key={row.id}><div><strong>{relationLabel(row,'user')} — {t(String(row.role))}</strong><p className="prose">{String(row.notes||'')}</p></div>{(row.role==='editor'?canAssignEditor:canManage||canAssignEditor)&&<div className="action-row"><button className="text-button" onClick={()=>edit(row)}>{t('edit')}</button><button className="text-button" disabled={remove.isPending} onClick={()=>remove.mutate(row)}>{t('removeAssignment')}</button></div>}</article>)}{remove.error&&<ErrorBox error={remove.error}/>}{editing!==undefined&&<Modal title={t('teamAssignments')} close={()=>setEditing(undefined)}><form className="form-grid" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><label><span>{t('person')}</span><select aria-label={t('person')} required value={person} onChange={e=>setPerson(e.target.value)}><option value="">{t('select')}</option>{users.data?.results.map(u=><option key={u.id} value={u.id}>{label(u)}</option>)}</select></label><label><span>{t('responsibility')}</span><select aria-label={t('responsibility')} value={role} onChange={e=>setRole(e.target.value)}>{responsibilities.filter(r=>r!=='editor'||canAssignEditor).map(r=><option key={r} value={r}>{t(r)}</option>)}</select></label><label className="full"><span>{t('notes')}</span><textarea aria-label={t('notes')} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{mutation.error&&<div className="full"><ErrorBox error={mutation.error}/></div>}{users.error&&<ErrorBox error={users.error}/>}<footer className="form-footer full"><button className="button primary" disabled={mutation.isPending}>{t('save')}</button></footer></form></Modal>}</div>
}
