import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {api,post,type Item,type Page,type Schema,type User} from './api'
import {useI18n} from './i18n'
import {ActionForm,Badge,ErrorBox,Loading,Modal,RecordForm,ResourceList} from './components'

export function DriveWorkspace({workspace,schema,can,user}:{workspace:string;schema:Schema;can:(p:string)=>boolean;user:User}){
 const {t}=useI18n();const client=useQueryClient();const [edit,setEdit]=useState<Item|null|undefined>();const [selected,setSelected]=useState<Item>();const [operation,setOperation]=useState('');const [scope,setScope]=useState('file');const [youtube,setYoutube]=useState(false);const [tab,setTab]=useState('drive')
 const connections=useQuery({queryKey:['drive-connections',workspace],queryFn:()=>api<Page>('storage/connections/',workspace)})
 const mutation=useMutation({mutationFn:async()=>{const response=await post<{url?:string}>(`storage/connections/${selected?.id}/actions/${operation}/`,workspace,{scope,youtube});if(response.url)window.location.assign(response.url)},onSuccess:()=>{setOperation('');void client.invalidateQueries()}})
 return <><div className="page-header"><h1>{t('integrations')}</h1>{can('manage_storage_connections')&&<button className="button primary" onClick={()=>setEdit(null)}>{t('addDriveConnection')}</button>}</div><div className="tabs">{['drive','ad-connections'].map(v=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{t(v==='drive'?'google_drive':'adConnections')}</button>)}</div>
 {tab==='drive'?<>{connections.isPending?<Loading/>:connections.error?<ErrorBox error={connections.error}/>:connections.data.results.map(row=><section className="panel drive-connection" key={row.id}><div className="section-heading"><h2>{String(row.name)}</h2><Badge value={row.status}/></div><div className="detail-grid">{['account_email','root_folder_id','shared_drive_id','last_sync'].map(key=><div key={key}><dt>{t(key)}</dt><dd>{String(row[key]||'—')}</dd></div>)}</div><p>{t('scope')}: {Array.isArray(row.scopes)?row.scopes.map(s=>String(s).split('/').pop()).join(', '):t('unsupported')}</p><p className="muted">{t('driveRootHint')}</p>{row.last_error?<ErrorBox error={row.last_error}/>:null}{can('manage_storage_connections')&&<div className="action-row"><button className="button primary" disabled={!user.capabilities.google_oauth} onClick={()=>{setSelected(row);setOperation('connect')}}>{t('connect')}</button><button className="button secondary" onClick={()=>setEdit(row)}>{t('edit')}</button>{['organize','sync','test','disconnect'].map(op=><button className="button secondary" key={op} disabled={row.status!=='connected'} onClick={()=>{setSelected(row);setOperation(op)}}>{t(op)}</button>)}</div>}{can('submit_version')&&<button className="button secondary" disabled={row.status!=='connected'} onClick={()=>{setSelected(row);setOperation('transfer')}}>{t('transfer')}</button>}{!user.capabilities.google_oauth&&<p>{t('googleNotConfigured')}</p>}</section>)}
 <ResourceList resource="storage/objects" workspace={workspace} schema={schema}/><ResourceList resource="storage/uploads" workspace={workspace} schema={schema}/><ResourceList resource="storage/syncs" workspace={workspace} schema={schema}/></>:<><section className="panel"><p>{t('providerTruth')}</p><p>{t('metaBeta')}</p></section><ResourceList resource="ad-connections" workspace={workspace} schema={schema}/></>}
 {edit!==undefined&&<Modal title={t('storage')} close={()=>setEdit(undefined)}><RecordForm resource="storage/connections" workspace={workspace} schema={schema} initial={edit||undefined} onDone={()=>setEdit(undefined)}/></Modal>}
 {selected&&operation&&operation!=='transfer'&&<Modal title={t(operation)} close={()=>setOperation('')}><form className="request-form" onSubmit={e=>{e.preventDefault();mutation.mutate()}}>{operation==='connect'?<><label><span>{t('scope')}</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="file">{t('scope_file')}</option><option value="full">{t('scope_full')}</option></select></label><label className="checkbox-label"><input type="checkbox" checked={youtube} onChange={e=>setYoutube(e.target.checked)}/>{t('youtube_scope')}</label></>:<p>{t('confirmCaption')}</p>}{mutation.error&&<ErrorBox error={mutation.error}/>}<button className="button primary" disabled={mutation.isPending}>{t('confirm')}</button></form></Modal>}
 {selected&&operation==='transfer'&&<ActionForm title={t('transfer')} workspace={workspace} onDone={()=>setOperation('')} fields={[{name:'version',related:'versions',required:true},{name:'provider',options:user.capabilities.youtube_publish&&(selected.scopes as string[]||[]).includes('https://www.googleapis.com/auth/youtube.upload')?['google_drive','youtube']:['google_drive'],required:true}]} run={data=>post(`storage/connections/${selected.id}/actions/transfer/`,workspace,{...data,idempotency_key:crypto.randomUUID()})}/>}
 </>
}
