import {useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery} from '@tanstack/react-query'
import {Search,ArrowUpRight,ChartNoAxesCombined} from 'lucide-react'
import {api} from './api'
import {useI18n} from './i18n'
import {Badge,ErrorBox,Loading} from './components'
type Observation={id:string;title:string;outcome:string;creative_type:string;sample_size:number;currency:string|null;interval_start:string|null;interval_end:string|null;latest_metrics:Record<string,number|null>}
type EvidenceData={results:Observation[];groups:{creative_type:string;outcome:string;sample_size:number}[];fatigue:{creative_id:string;title:string;signals:{metric:string;change_percent?:number;value?:number}[]}[]}
export function Evidence({workspace}:{workspace:string}){
 const {t,lang}=useI18n();const [q,setQ]=useState('');const [outcome,setOutcome]=useState('')
 const query=useQuery({queryKey:['evidence',workspace,q,outcome],queryFn:()=>api<EvidenceData>('evidence/?'+new URLSearchParams({q,outcome}),workspace)})
 const number=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(n)
 return <><div className="section-heading"><h2>{t('evidence')}</h2><ChartNoAxesCombined size={20}/></div><div className="list-toolbar"><div className="search-input"><Search size={16}/><input aria-label={t('search')} placeholder={t('searchPlaceholder')} value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label={t('outcome')} style={{maxWidth:180}} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">{t('all')}</option>{['winner','loser','neutral','fatigued'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></div>{query.isPending?<Loading/>:query.error?<ErrorBox error={query.error}/>:<><section className="panel"><div className="table-scroll"><table><thead><tr>{['creative','outcome','sampleSize','currency','CTR','ROAS','CPA','interval_end'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{query.data.results.map(row=><tr key={row.id}><td><Link className="record-link" to={'/creatives/'+row.id}>{row.title}</Link></td><td>{row.outcome?<Badge value={row.outcome}/>:'—'}</td><td>{number(row.sample_size)}</td><td>{row.currency||'—'}</td>{['ctr','roas','cpa'].map(metric=><td key={metric}>{number(row.latest_metrics[metric])}</td>)}<td>{row.interval_end?new Intl.DateTimeFormat(lang,{dateStyle:'medium'}).format(new Date(row.interval_end)):'—'}</td></tr>)}</tbody></table></div><p className="muted small" style={{marginTop:20}}>{t('evidenceLimitations')}</p></section><section className="panel" style={{marginTop:20}}><h2>{t('fatigued')}</h2>{query.data.fatigue.length?query.data.fatigue.map(row=><Link className="search-result" to={'/creatives/'+row.creative_id} key={row.creative_id}><span><strong>{row.title}</strong><small>{row.signals.map(s=>s.metric.toUpperCase()+': '+number(s.change_percent??s.value)+(s.change_percent!==undefined?'%':'')).join(' · ')}</small></span><ArrowUpRight size={17}/></Link>):<p className="muted small" style={{marginTop:15}}>{t('noResults')}</p>}</section><section className="panel" style={{marginTop:20}}><h2>{t('patterns')}</h2><div className="table-scroll"><table><thead><tr><th>{t('creative_type')}</th><th>{t('outcome')}</th><th>{t('sampleSize')}</th></tr></thead><tbody>{query.data.groups.map((g,i)=><tr key={i}><td>{t(g.creative_type)}</td><td>{t(g.outcome||'neutral')}</td><td>{number(g.sample_size)}</td></tr>)}</tbody></table></div></section></>}</>
}
