import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api,post,label,type Item,type Page,type User} from './api'
import {useI18n} from './i18n'
import {ActionForm,Badge,ErrorBox,Modal} from './components'

export function ProfilePage({user}:{user:User}){
 const {t}=useI18n();const client=useQueryClient();const [name,setName]=useState(user.display_name);const [profile,setProfile]=useState<Record<string,unknown>>(user.profile);const [password,setPassword]=useState(false)
 const mutation=useMutation({mutationFn:()=>api('me/','',{method:'PATCH',body:JSON.stringify({display_name:name,profile})}),onSuccess:()=>void client.invalidateQueries({queryKey:['session']})})
 return <><div className="page-header"><h1>{t('profile')}</h1></div><section className="panel"><form className="form-grid" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><label><span>{t('display_name')}</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>{t('email')}</span><input readOnly value={user.email}/></label>{['avatar','job_title','phone','timezone','locale'].map(key=><label key={key}><span>{t(key)}</span><input type={key==='avatar'?'url':'text'} value={String(profile[key]||'')} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label><span>{t('preferred_language')}</span><select value={String(profile.preferred_language)} onChange={e=>setProfile({...profile,preferred_language:e.target.value})}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label><label className="checkbox-label"><input type="checkbox" checked={(profile.notification_preferences as Record<string,unknown>)?.in_app!==false} onChange={e=>setProfile({...profile,notification_preferences:{...(profile.notification_preferences as object||{}),in_app:e.target.checked}})}/>{t('inAppNotifications')}</label>{mutation.error&&<ErrorBox error={mutation.error}/>} {mutation.isSuccess&&<p role="status">{t('success')}</p>}<footer className="form-footer full"><button className="button primary" disabled={mutation.isPending}>{t('save')}</button><button type="button" className="button secondary" onClick={()=>setPassword(true)}>{t('changePassword')}</button></footer></form></section>{password&&<ActionForm title={t('changePassword')} workspace="" onDone={()=>setPassword(false)} fields={[{name:'old_password',kind:'password',required:true},{name:'new_password',kind:'password',required:true}]} run={data=>post('me/','',data)}/>}</>
}

export function TeamPage({workspace,user}:{workspace:string;user:User}){
 const {t}=useI18n();const client=useQueryClient();const [selected,setSelected]=useState<Item|null|undefined>();const [values,setValues]=useState<Record<string,unknown>>({});const [newWorkspace,setNewWorkspace]=useState(false)
 const members=useQuery({queryKey:['members',workspace],queryFn:()=>api<Page>(`workspaces/${workspace}/members/`),enabled:!!workspace})
 const brands=useQuery({queryKey:['brands',workspace],queryFn:()=>api<Page>('brands/',workspace),enabled:!!workspace})
 const mutation=useMutation({mutationFn:()=>post(`workspaces/${workspace}/members/`,'',values),onSuccess:()=>{void client.invalidateQueries();setSelected(undefined)}})
 const edit=(member:Item|null)=>{setSelected(member);setValues(member?{email:member.email,name:member.name,role:member.role,active:member.active,brand_restricted:member.brand_restricted,brands:member.brands}:{email:'',name:'',role:'viewer',active:true,brands:[],brand_restricted:false});mutation.reset()}
 return <><div className="page-header"><h1>{t('administration')}</h1><div className="action-row">{workspace&&<button className="button primary" onClick={()=>edit(null)}>{t('invite')}</button>}{user.is_superuser&&<button className="button secondary" onClick={()=>setNewWorkspace(true)}>{t('newWorkspace')}</button>}</div></div><section className="panel">{members.error&&<ErrorBox error={members.error}/>} {members.data?.results.map(row=><div className="member-row" key={row.id}><span className="avatar">{label(row).slice(0,2)}</span><div><strong>{String(row.name)}</strong><p>{String(row.email)}</p></div><Badge value={row.role}/><span>{t(row.active?'active':'disconnected')}</span><button className="button secondary" onClick={()=>edit(row)}>{t('edit')}</button></div>)}</section>
 {selected!==undefined&&<Modal title={t(selected?'edit':'invite')} close={()=>setSelected(undefined)}><form className="form-grid" onSubmit={e=>{e.preventDefault();mutation.mutate()}}>{['email','name'].map(key=><label key={key}><span>{t(key)}</span><input type={key==='email'?'email':'text'} readOnly={!!selected&&key==='email'} required={key==='email'} value={String(values[key]||'')} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}<label><span>{t('role')}</span><select value={String(values.role)} onChange={e=>setValues({...values,role:e.target.value})}>{['manager','media_buyer','editor','reviewer','requester','viewer'].map(v=><option value={v} key={v}>{t(v)}</option>)}</select></label>{['active','brand_restricted'].map(key=><label className="checkbox-label" key={key}><input type="checkbox" checked={!!values[key]} onChange={e=>setValues({...values,[key]:e.target.checked})}/>{t(key)}</label>)}{!!values.brand_restricted&&<fieldset className="full platform-choices"><legend>{t('brands')}</legend>{brands.data?.results.map(b=><label key={b.id}><input type="checkbox" checked={(values.brands as string[]).includes(b.id)} onChange={e=>setValues({...values,brands:e.target.checked?[...(values.brands as string[]),b.id]:(values.brands as string[]).filter(id=>id!==b.id)})}/>{label(b)}</label>)}</fieldset>}
 {selected&&<label className="checkbox-label"><input type="checkbox" checked={!!values.reset_password} onChange={e=>setValues({...values,reset_password:e.target.checked})}/>{t('resetTemporaryPassword')}</label>}{(!selected||!!values.reset_password)&&<label><span>{t('password')}</span><input type="password" required minLength={8} autoComplete="new-password" value={String(values.password||'')} onChange={e=>setValues({...values,password:e.target.value})}/></label>}{mutation.error&&<div className="full"><ErrorBox error={mutation.error}/></div>}<footer className="form-footer full"><button className="button primary" disabled={mutation.isPending}>{t('save')}</button></footer></form></Modal>}
 {newWorkspace&&<ActionForm title={t('newWorkspace')} workspace="" onDone={()=>setNewWorkspace(false)} fields={[{name:'name',required:true},{name:'slug',required:true}]} run={data=>post('workspaces/','',data)}/>}
 </>
}
