# Generated by Django 5.2.17 on 2026-09-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('creatives', '0001_initial'),
        ('integrations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('manual', 'manual'), ('meta', 'meta'), ('tiktok', 'tiktok'), ('youtube', 'youtube'), ('google_ads', 'google_ads'), ('snapchat', 'snapchat'), ('pinterest', 'pinterest'), ('linkedin', 'linkedin'), ('other', 'other')], default='manual', max_length=40)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=200)),
                ('campaign_id', models.CharField(blank=True, default='', max_length=200)),
                ('adset_id', models.CharField(blank=True, default='', max_length=200)),
                ('ad_id', models.CharField(blank=True, default='', max_length=200)),
                ('destination_url', models.URLField(blank=True)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('active', 'active'), ('archived', 'archived')], default='draft', max_length=40)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.adconnection')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creativeversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, default='manual', max_length=200)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('spend', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('link_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('video_views', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='performance.deployment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('winner', 'winner'), ('loser', 'loser'), ('neutral', 'neutral'), ('fatigued', 'fatigued'), ('refresh_requested', 'refresh_requested')], default='winner', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='creatives.creative')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='performance.performancesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='performancesnapshot',
            constraint=models.UniqueConstraint(fields=('deployment', 'interval_start', 'interval_end'), name='performance_window'),
        ),
        migrations.AddConstraint(
            model_name='performancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('interval_end__gt', models.F('interval_start'))), name='performance_interval'),
        ),
    ]
